name: Build & Deploy Eleventy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js current
        uses: actions/setup-node@v3
        with:
          # avoid sass issue
          node-version: "20.x"

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run buildprod

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          allow_empty_commit: true
          publish_dir: public
